Repository Caoa-Montadora-de-Veiculos-Ltda/Protheus, pull requests merged in 2024-03, with the labels that each got.

#396 CHG0033399 | GFEA065.001 | Gravação da TES no Documento de Frete
  Ponto de Entrada/GFEA065_PE.prw
Labels: correção, SIGAGFE

#397 CHG0033413 | Travamento na Avaliação de Credito do Cliente
  Ponto de Entrada/M410PVNF_PE.prw
  SIGAFAT/Função/ZFATF014.PRW
Labels: correção

#401 CHG003339 | VEIA060CAOA_001 | Parâmetro de comissão de venda
  Ponto de Entrada/PEDVEI011_PE.prw
  Ponto de Entrada/VEIA060CAOA_PE.prw
Labels: melhoria
