Repository Caoa-Montadora-de-Veiculos-Ltda/Protheus, pull requests merged in 2024-10, with the labels that each got.

#671 Tratativa para tabela do tipo 007, para não considerar IPI
  SIGAPEC/Funcao/ZPECF016.prw
Labels: melhoria, protheus, SIGAFAT

#679 Ajustado Pis ecofins para zona franca na tabela 007
  SIGAPEC/Funcao/ZPECF016.prw
Labels: melhoria, protheus, SIGAPEC

#686 GAP178|Rastreio de veículo no ERP
  SIGAVEI/Função/ZVEIF005.PRW
Labels: melhoria, protheus, SIGAFAT

#687 GAP178|Rastreio veículo ERP
  SIGAVEI/Função/ZVEIF005.PRW
Labels: melhoria, protheus, SIGAFAT

#688 GAP178|Rastreamento Veiculo ERP
  SIGAVEI/Função/ZVEIF005.PRW
Labels: melhoria, protheus, SIGAFAT

#695 GAP285 | Lentidão no relatório de BO
  SIGAPEC/Funcao/ZPECF035.prw
Labels: correção, protheus, SIGAPEC

#697 GAP286
  SIGAPEC/Funcao/ZPECFUNA.PRW
Labels: correção, protheus, SIGAPEC
