Repository Caoa-Montadora-de-Veiculos-Ltda/Protheus, pull requests merged in 2024-06, with the labels that each got.

#497 GAP114 | ASIA V2 - Inclusão de novos campos na integração
  .vscode/.advpl/_binary_class.prw
  .vscode/.advpl/_binary_functions.prw
  Ponto de Entrada/EICDI500_PE.PRW
  SIGAEIC/Funcao/ZEICF025.PRW
Labels: melhoria, SIGAEIC

#510 GAP196 | Relatório de B.O da empresa 90
  SIGAPEC/Relatorio/ZPECR006.prw
Labels: correção, SIGAPEC

#508 CHG0033742| EIC003.013 | Erro ao integrar invoice antecipada - CBU Chery
  SIGAEIC/Funcao/CMVEIC01.prw
Labels: correção, SIGAEIC

#521 GAP202 | Correção da Parcela financeira de integração com o SAP.
  Ponto de Entrada/VEIA060CAOA_PE.prw
Labels: correção, SIGAFIN

#522 GFEA042.001 | PE para chamar a função ZGFEF008 - Alterar peso bruto
  Ponto de Entrada/GFEA042_PE.prw
Labels: correção, SIGAGFE

#524 GAP204 | Correção no Controle de Semaforo
  SIGAPEC/Funcao/ZPECF013.prw
Labels: correção, SIGAFAT

#525 FIS002.003 | Inclusão de campo grupo de cliente no rel. fiscal
  Integracoes/MasterSaf/CMVMSF01.prw
  Integracoes/MasterSaf/CMVMSF06.prw
  Ponto de Entrada/GFEA042_PE.prw
  Ponto de Entrada/VEIA060CAOA_PE.prw
  SIGACOM/Função/ZCOMF056.prw
  SIGAGFE/Funcao/ZGFEF008.PRW
  SIGAPEC/Funcao/ZPECF013.prw
Labels: melhoria, SIGAFIS

#527 GAP205 | SAFX08 campo valor unitário p/ NFs que possui exoneração de ICMS ZFM
  Integracoes/MasterSaf/CMVMSF06.prw
Labels: correção, SIGAFIS

#529 GAP206 | Integração do SAP para Título de Veículo PNE sem Placa
  Ponto de Entrada/VEIA060CAOA_PE.prw
Labels: correção, SIGAFIN, SIGAVEI
