Repository Caoa-Montadora-de-Veiculos-Ltda/Protheus, pull requests merged in 2024-07, with the labels that each got.

#531 GAP207 | Entradas das notas HMB (loja 90 módulo compras) , o armazém "local de Entrada" não está obedecendo o armazém indicado.
  Genericos/Funcao/ZGENFTE.prw
Labels: correção, protheus, SIGACOM, SIGAPEC

#532 GAP098 | Revitalização Onda de Pedidos - Versão 3.0
  .vscode/.gitignore
  Integracoes/RgLog - SILT/ZWSR007.PRW
  Integracoes/RgLog - SILT/ZWSR009.PRW
  Ponto de Entrada/CRMA980_PE.PRW
  Ponto de Entrada/OA011LEG.PRW
  Ponto de Entrada/OX001RES_PE.prw
  Ponto de Entrada/OX004AIP_PE.prw
  Ponto de Entrada/OX004APV_PE.prw
  Ponto de Entrada/VEIA060CAOA_PE.prw
  SIGAFAT/Função/ZFATF012.prw
  SIGAFAT/Função/ZFATF014.PRW
  SIGAPEC/Classes/SaldoCAOAPEC.PRW
  SIGAPEC/Funcao/ZPECF008.PRW
  SIGAPEC/Funcao/ZPECF011.PRW
  SIGAPEC/Funcao/ZPECF013.prw
  SIGAPEC/Funcao/ZPECF031.prw
  SIGAPEC/Funcao/ZPECF036.prw
  SIGAPEC/Funcao/ZPECFUNA.PRW
Labels: correção, SIGAPEC

#538 WSR003.001 | Diferenciação do Log para as Empresas
  Integracoes/RgLog - SILT/ZWSR003.prw
Labels: correção, SIGAPEC

#540 EICDI500.001 | Campo D1_XCASE em branco quando o campo W8_XCASE estiver em branco
  Ponto de Entrada/EICDI500_PE.PRW
Labels: correção, protheus, SIGAEIC

#542 EIC003.006 | Integração Contas a Pagar Z7_SERORI="EIC"
  Integracoes/SAP/ZGENSAP.prw
Labels: correção, protheus, SIGAEIC

#544 RGLOG001.002 | O pedido foi atendido parcialmente não gerou B.O para item substituído
  SIGAPEC/Funcao/ZPECF008.PRW
Labels: correção, SIGAPEC

#546 GAP213 | Ajuste no Fonte para validação da Empresa para criação da Tabela SZ7.
  Ponto de Entrada/CRMA980_PE.PRW
Labels: correção, protheus, SIGAFAT, SIGAPEC

#548 GAP214 | Lentidão na rotina de aprovação do Pedido de Compras
  SIGACOM/Função/ZCOMF029.prw
  SIGACOM/Relatorio/ZCOMR001.PRW
  SIGACOM/Relatorio/ZCOMR004.PRW
Labels: correção, SIGACOM

#549 Gap136 | API Cadastro de Cliente
  Genericos/Funcao/ZWSRFUN.PRW
  Integracoes/Protheus/ZRESTSA1.PRW
  Integracoes/Protheus/ZWSR016.PRW
Labels: melhoria, protheus

#423 GAP156 | Problema no relatório Customizado - ZFATR005 devido ao ponto de entrada
  Ponto de Entrada/PEDVEI011_PE.prw
Labels: correção, protheus, SIGAFAT

#564 PEC011.002 | Erro ao enviar a confirmação da separação - errorCode : 999
  SIGAPEC/Funcao/ZPECF011.PRW
Labels: correção, protheus, SIGAPEC

#565 FIS003.010 | Extração de Relatório não esta extraindo o CST ICMS e CST IPI
  Ponto de Entrada/COMCOLSD.prw
  Ponto de Entrada/M103PCIT.prw
Labels: correção, protheus, SIGAFIS
